### ISSUE TITLE
建议老师可以按照免杀的方式生成相关测试包

### ISSUE THREAD

**Issue by wjl110** [midisec/BypassAnti-Virus#1]

**Comment by midisec** [comment]
谢谢你的建议，目前免杀方式(callback)在VS2022环境下能够直接进行编译。该如何制作测试包？我缺少相应的经验。

**Comment by wjl110** [comment]
编译成java可执行的jar包，多平台都可以使用

**Comment by midisec** [comment]
这样是很方便，但是目前这种window的api在其他平台貌似不能进行调用编译，未来若有其他方法将会制作成这种方式，感谢。

**Comment by wjl110** [comment]
> 这样是很方便，但是目前这种window的api在其他平台貌似不能进行调用编译，未来若有其他方法将会制作成这种方式，感谢。

OK👌
