### ISSUE TITLE
是不是少了个文件呢

### ISSUE THREAD

**Issue by Wo-HaHa** [midisec/BypassAnti-Virus#3]
ip2string.h

**Comment by midisec** [comment]
这是win环境下自带的头文件，我们测试使用的是vs2022版本。可以尝试修改vs里面Windows sdk版本，我们使用的是10。如果解决不了问题，或许可能是相关依赖/环境没有安装，安装vs时工作负载选择: 通过Windows平台开发、.net桌面开发、使用c++的桌面开发。
官方详情: https://docs.microsoft.com/zh-cn/windows/win32/api/ip2string/nf-ip2string-rtlethernetaddresstostringa
