### ISSUE TITLE
大哥问下遇到这样的报错该怎么解决呀

### ISSUE THREAD

**Issue by XiaoXueSheng010** [midisec/BypassAnti-Virus#6]
在加载的模块中为找到当前堆栈帧，无法显示此位置的源代码

**Comment by midisec** [comment]
使用的是什么环境? 具体是哪一行报错的?

**Comment by XiaoXueSheng010** [comment]
> 使用的是什么环境? 具体是哪一行报错的?

使用的是VS2019，报的是0xC0000096: Privileged instruction异常。

**Comment by zxc135781** [comment]
+1

**Comment by midisec** [comment]
> 

所以版本都无法编译吗，还是具体特定的哪个版本。由于这边使用的编译器不同，有可能是编译器差异导致的。

**Comment by zxc135781** [comment]
> > 
> 
> 所以版本都无法编译吗，还是具体特定的哪个版本。由于这边使用的编译器不同，有可能是编译器差异导致的。

我这里是64位的可以编译运行成功，32位的运行会闪退，然后调试报相同的错误

**Comment by midisec** [comment]
大概率原因是由于部分回调函数不兼容32位的加载。
在使用32位的payload时，尝试打印一下内存中的信息，若内存中的内容正常则说明相应的回调函数可能不支持32位的，可以尝试换另外的回调函数加载。
`
printf("[*] Hexdump: ");
	for (int i = 0; i < num * 16; i++) {
	    printf("%02X ", ((unsigned char*)ha)[i]);
	}`
