### ISSUE TITLE
虚拟机运行提示缺少dll   

### ISSUE THREAD

**Issue by sharcmz** [midisec/BypassAnti-Virus#7]
vcruntime140d.dll

**Comment by midisec** [comment]
当时的编译环境为：VS2022、Windows SDK 10.0、C++14，虚拟机中应该是缺少相应的环境

**Comment by sharcmz** [comment]
> 当时的编译环境为：VS2022、Windows SDK 10.0、C++14，虚拟机中应该是缺少相应的环境

 了解了

**Comment by sharcmz** [comment]
> 当时的编译环境为：VS2022、Windows SDK 10.0、C++14，虚拟机中应该是缺少相应的环境

 谢谢老哥
