### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by 1363389144** [midisec/BypassAnti-Virus#8]
![image](https://user-images.githubusercontent.com/65819218/178150568-7f16441a-adb9-4fc7-97d0-8dbb0ea7c8a4.png)
老哥 这个怎么解决

**Comment by midisec** [comment]
看起来是没有找到UUidFromStringA的符号表，该函数是在RPCRT4.dll模块下的，缺少相应的dll导致，可以寻找相应的dll或者安装一个完整的C++环境。之前我用的环境是VS2022，在安装时选择C++环境、windows开发环境，里面对windows中常见的函数都有提供。

**Comment by 1363389144** [comment]
很奇怪，我重装了vs2022，关于c++的都勾上了，检查了RPCRT4.dll 这个文件存在 但是还是一样的提示

**Comment by midisec** [comment]
在VS2022中新建C++空项目，添加源文件之后，编译尝试一下

**Comment by 1363389144** [comment]
单独添加这个源文件 是可以正常编译的，测试了下，问题应该在数组那里，加上这条就编译错误
![image](https://user-images.githubusercontent.com/65819218/178298653-4ea2c4ab-a15e-45bc-b7a1-b5744939263e.png)

**Comment by midisec** [comment]
在VS编译时，具体的报错行数以及内容看一下

**Comment by 1363389144** [comment]
感谢老哥，今早打开电脑就能编译了emmm

**Comment by 1363389144** [comment]
有啥方法过wdf吗，我试了下，如果隐藏窗口，360就报，有什么思路过掉嘛emmm

**Comment by midisec** [comment]
隐藏黑框的方法：https://github.com/midisec/BypassAnti-Virus/blob/main/common/VS%E4%B8%AD%E8%BF%90%E8%A1%8C%E5%8E%BB%E9%99%A4%E9%BB%91%E6%A1%86.md
可以尝试V0.2版本免杀，我在近期测试了是可以正常绕过的

**Comment by 1363389144** [comment]
![image](https://user-images.githubusercontent.com/65819218/178762559-39a1bf78-a979-4f35-8b1f-f975bf9bef1e.png)
![image](https://user-images.githubusercontent.com/65819218/178762476-3c596cfc-8d0d-48f5-b668-a192f12ad94c.png)
emm设置了入口点 还是谈窗口

**Comment by 1363389144** [comment]
已解决，在代码头加入#pragma comment( linker, "/subsystem:\"windows\" /entry:\"mainCRTStartup\"" )
